import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";

const calSans = localFont({
	src: "./assets/fonts/CalSans-SemiBold.woff2",
	variable: "--font-title",
});
const matter = localFont({
	src: [
		{
			path: "./assets/fonts/Matter-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "./assets/fonts/Matter-Medium.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "./assets/fonts/Matter-SemiBold.woff2",
			weight: "600",
			style: "normal",
		},
		{
			path: "./assets/fonts/Matter-Bold.woff2",
			weight: "700",
			style: "normal",
		},
	],
	variable: "--font-body",
});

export const metadata: Metadata = {
	title: "Coffeelivery",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${matter.variable} ${calSans.variable}`}>
				{children}
			</body>
		</html>
	);
}
